version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: itchy_pup
      POSTGRES_USER: itchy_pup
      POSTGRES_PASSWORD: itchy_pup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 